#---
#sharding:
#  jdbc:
#    datasource:
#      ds0:
#        password: z012345
#        #type: org.apache.commons.dbcp.BasicDataSource
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbcUrl: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
#        username: root
#      ds1:
#        password: z012345
#        #type: org.apache.commons.dbcp.BasicDataSource
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbcUrl: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
#        username: root
#      names: ds0,ds1
#    config:
#      sharding:
#        tables:
#          t_order:
#            table-strategy:
#              inline:
#                #分表策略--对那个字段进行分表
#                sharding-column: order_id
#                #分表的表达式
#                algorithm-expression: t_order_$->{order_id % 2}
#            #分表对应的字段名
#            key-generator-column-name: order_id
#            #分表策略--ds$->{0..1}.t_order_$->{0..1}代表是那个库下面的那个表
#            actual-data-nodes: ds$->{0..1}.t_order_$->{0..1}
#        default-database-strategy:
#          inline:
#            #分库策略--对那个字段进行分库
#            sharding-column: user_id
#            #分库对user_id % 2进行分库选择
#            algorithm-expression: ds$->{user_id % 2}
